-- Insert all games data from games.json (ignore duplicates)
INSERT INTO "public"."CasinoGame" (
    "id",
    "name",
    "description",
    "api_name",
    "logo",
    "category",
    "rtp",
    "max_win",
    "min_stake",
    "max_take",
    "release_date",
    "provider",
    "features",
    "is_new",
    "fetch_results_url",
    "created_at",
    "updated_at"
) VALUES
    (
        gen_random_uuid(),
        'Crazy Time',
        'Crazy Time by Evolution is the world''s most popular online casino game show. The game features a Money Wheel, a Top Slot for added multipliers, and four exciting bonus games.',
        'crazytime',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_60,c_scale,c_crop,h_153,w_190/CasinoScores/crazy-time-thumbnail.png',
        'TRACKED GAME SHOWS',
        '95.41%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Cash Hunt Bonus", "Pachinko Bonus", "Coin Flip Bonus", "Crazy Time Bonus"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/crazytime',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Ice Fishing',
        'Ice Fishing Live is Evolution''s latest live casino game show, combining a fortune wheel mechanic with immersive, theme-driven bonus rounds.',
        'icefishing',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/ice-fishing/logo-ice-fishing.png',
        'TRACKED GAME SHOWS',
        'Not officially confirmed',
        NULL,
        0.1,
        1000.0,
        'Expected August 2025',
        'evolution',
        '["Lil'' Blues Bonus", "Big Oranges Bonus", "Huge Reds Bonus"]',
        true,
        'https://api.casinoscores.com/svc-evolution-game-events/api/icefishing',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Monopoly Live',
        'Monopoly Live is another take on the popular money wheel game Dreamcatcher from Evolution, featuring a bonus game on a 3D Monopoly board.',
        'monopolylive',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_200,f_auto,q_auto,c_scale/CasinoScores/Monopoly%20Live/monopoly-live-thumbnail-2.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Chance Card Feature", "2 ROLLS Bonus Game", "4 ROLLS Bonus Game"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/monopolylive',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Lightning Storm',
        'The main objective of Lightning Storm is to predict the segment on which the wheel will stop. The segments can either provide instant payouts or lead to one of the five bonus games.',
        'lightningstorm',
        'https://res.cloudinary.com/dlkdffnou/image/upload/v1721032732/lightning-storm/lightning-storm-logo-min.png',
        'TRACKED GAME SHOWS',
        '97.44%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Hot Spot Bonus", "Monster Mash Bonus", "Battery Charger Bonus", "Fireball Bonus", "Lightning Storm Bonus"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/lightningstorm',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Adventures Beyond Wonderland',
        'This live dealer game from Playtech allows players to meet up virtually with the Mad Hatter, Alice, the White Rabbit, and more of the crazy characters, as well as win cash prizes.',
        'adventuresbeyondwonderland',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Adventures%20Beyond%20Wonderland/adventures-beyond-wonderland-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'playtech',
        '["Four Bonus Rounds", "Two Mystery Symbols", "Live Dealers in Costume"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/adventuresbeyondwonderland',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Monopoly Big Baller',
        'MONOPOLY Big Baller marries the popular game show MONOPOLY Live with the lottery success Megaball. Play a bingo-style game with a live host and Mr. MONOPOLY himself.',
        'monopolybigballer',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/MonopolyBigBaller/monopoly-big-baller-logo-thumbnail.png',
        'TRACKED GAME SHOWS',
        '96.10%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Chance / Free Space Cards", "3 and 5 Rolls Bonus Cards", "Three Multiplier Types"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/monopolybigballer',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Sweet Bonanza Candyland',
        'Sweet Bonanza Candyland offers a visually rich, candy-themed adventure, combining the thrill of real-time gaming with the convenience of online play.',
        'sweetbonanzacandyland',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Sweet%20Bonanza%20Candyland/sweet_bonanza_candyland_logo-min-compressed.png',
        'TRACKED GAME SHOWS',
        '96.95%',
        NULL,
        0.2,
        1000.0,
        NULL,
        'pragmatic-play',
        '["Sugar Bomb", "Bubble Surprise", "Candy Drop Bonus", "Sweet Spins Bonus"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/sweetbonanzacandyland',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Fortune Roulette',
        'Pragmatic Studios'' Fortune Roulette is a clear competitor to games like Fireball Roulette and Lightning Roulette. It is a standard European Roulette table with added excitement.',
        'fortuneroulette',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/fortune-roulette/fortune-roulette-logo-min.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'pragmatic-play',
        '["Fortune Multipliers", "Chest Feature", "Bonus Game"]',
        true,
        'https://api.casinoscores.com/svc-evolution-game-events/api/fortuneroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Lightning Bac Bo',
        'Lightning Bac Bo is Evolution''s fast-paced, dice-driven twist on Baccarat, where every round delivers guaranteed Lightning multipliers between 2x and 8x.',
        'lightningbacbo',
        'https://res.cloudinary.com/dlkdffnou/image/upload/f_auto,q_auto,c_scale,w_auto/lightning-bac-bo/lightning-bac-bo-logo.png',
        'TRACKED GAME SHOWS',
        '98.87% (Player/Banker), 95.52% (Tie)',
        NULL,
        1.0,
        5000.0,
        NULL,
        'evolution',
        '["Guaranteed Lightning Multipliers (2x-8x)", "Dice-based gameplay", "Tie bet with high potential payout"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/lightningbacbo',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Treasure Island',
        NULL,
        'treasureisland',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,c_scale/Treasure%20Island/treasure-island-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'pragmatic-play',
        NULL,
        true,
        'https://api.casinoscores.com/svc-evolution-game-events/api/treasureisland',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Super Color Game',
        'Super Color Game is a new live casino game by Evolution that features three six-sided dice in yellow, white, pink, blue, red, and green. You predict which colors or combinations will land face-up.',
        'supercolorgame',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/super-color-game/super-color-logo.png',
        'TRACKED GAME SHOWS',
        '95.62%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Three six-sided colored dice", "Single, Double, and Triple bets", "Up to 18 multipliers applied per round"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/supercolorgame',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Dream Catcher',
        'Dream Catcher is an innovative and captivating live casino game that blends the simplicity of a money wheel with the excitement of real-time interactive gameplay.',
        'dreamcatcher',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/dreamcatcher.png',
        'TRACKED GAME SHOWS',
        '96.58%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Large vertical money wheel", "2x and 7x win multiplier segments", "Live host interaction"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/dreamcatcher',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Marble Race',
        'Marble Race is a fast-paced, visually engaging betting game that blends colour, movement, and unpredictability. Six marbles in different colours race down an obstacle-filled track.',
        'marblerace',
        'https://res.cloudinary.com/dlkdffnou/image/upload/f_auto,q_auto,w_auto,c_scale/Marble%20Race/marble-race-logo-min.png',
        'TRACKED GAME SHOWS',
        '95.83% (1st Place), 93.33% (1st & 2nd)',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Six colored marbles race", "Obstacle-filled track", "Bet on 1st place or 1st & 2nd place"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/marblerace',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Speed Baccarat A',
        'This baccarat variant combines traditional rules with lightning-fast gameplay and features rounds lasting less than 30 seconds.',
        'speedbaccarat',
        'https://res.cloudinary.com/dlkdffnou/image/upload/f_auto,q_auto,w_auto,c_scale/Speed%20Baccarat/speed-baccarat-logo.png',
        'TRACKED GAME SHOWS',
        'Up to 98.94%',
        NULL,
        1.0,
        5000.0,
        NULL,
        'evolution',
        '["Fast-paced rounds (under 30s)", "High RTP", "Side bets like Perfect Pairs"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/speedbaccarat',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Super Andar Bahar',
        'The objective is to predict whether the card that appears first on the Andar (inside) or Bahar (outside) side will match the rank of the ''Joker'' card.',
        'superandarbahar',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Andar%20Bahar/super-andar-bahar-logo-min.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Based on traditional Indian card game", "Side bets on number of cards", "Random multipliers"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/superandarbahar',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Crazy Balls',
        'Crazy Balls Live Video has 60 numbered balls launched from a bingo machine. When the game begins, only 20 numbered balls shoot out, striking off similar numbers from your eight cards.',
        'crazyballs',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/crazy-balls/crazy_balls_logo_1__new.png',
        'TRACKED GAME SHOWS',
        '95.54% - 96.49%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Bingo-style gameplay", "Four bonus rounds from Crazy Time", "Three types of multipliers"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/crazyballs',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Bac Bo',
        'Bac Bo replaces familiar cards from baccarat with four dice placed in an individual automatic shaker set in an Asian theme. The final result is the sum of each side''s two dice.',
        'bacbo',
        'https://res.cloudinary.com/dlkdffnou/image/upload/v1740479979/Bac%20Bo/bac-bo-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        1.0,
        5000.0,
        NULL,
        'evolution',
        '["Combination of Baccarat and Sic Bo", "Uses dice instead of cards", "Tie bet with high potential payout"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/bacbo',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Lightning Dice',
        'Lightning Dice brings a fresh twist to the classic dice game by incorporating dynamic gameplay and impressive win multipliers up to 1,000x.',
        'lightningdice',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/lightning-dice/lightning-dice-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        1000.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Three dice rolled in a ''Lightning Tower''", "Random Lightning Multipliers (up to 1,000x)", "Interactive Interface"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/lightningdice',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Auto Roulette',
        'Auto Roulette by Evolution Gaming is a streamlined version of classic roulette that operates seamlessly without a live dealer, offering players constant action with rapid rounds.',
        'autoroulette',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/auto-roulette/auto-roulette-logo_1.png',
        'TRACKED GAME SHOWS',
        '97.30%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Automated wheel, no dealer", "Fast-paced rounds", "Available 24/7"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/autoroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Fireball Roulette',
        'Evolution Fireball Roulette is a classic European Roulette with a twist. A Straight up bet is required to trigger the Bonus game.',
        'fireballroulette',
        'https://res.cloudinary.com/dlkdffnou/image/upload/v1746474611/Fireball%20Roulette/fireball-roulette-logo-min.png',
        'TRACKED GAME SHOWS',
        '97.00% (Straight Up), 97.30% (Other)',
        2500.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Fireball Bonus Round", "Fireball Chaser Bet", "Multipliers up to 2,500x in bonus"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/fireballroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Super Sic Bo',
        'Super Sic Bo is one of Evolution Gaming''s most popular games, utilising live dice rolls and fantastic multipliers.',
        'supersicbo',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/SuperSicBo/superSicBoLogoo.png',
        'TRACKED GAME SHOWS',
        'Up to 97.22%',
        999.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Live dice rolls", "Random multipliers up to 999x", "Wide range of betting options"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/supersicbo',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Funky Time',
        'The game features a one-of-a-kind DigiWheel and a different set of bonus rounds, including BAR, Stayin'' Alive, Disco, and VIP Disco.',
        'funkytime',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,c_scale/CasinoScores/Funky%20Time/funky_time_logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["DigiWheel", "BAR Bonus", "Stayin'' Alive Bonus", "Disco Bonus", "VIP Disco Bonus"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/funkytime',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Mega Roulette',
        'Mega Roulette by Pragmatic Play delivers an extra twist on the classic gameplay, with multipliers and the chance to win even bigger payouts.',
        'megaroulette',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Mega%20Roulette/mega-roulette-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        500.0,
        0.1,
        1000.0,
        NULL,
        'pragmatic-play',
        '["Up to five random multipliers per spin", "Multipliers from 50x to 500x", "Live dealer format"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/megaroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Mega Wheel',
        'A live dealer game that offers exciting prizes, Mega Wheel is easy for anyone to play. The aim is for players to correctly predict where the wheel will land on every spin.',
        'megawheel',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/mega_wheel_logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        500.0,
        0.1,
        1000.0,
        NULL,
        'pragmatic-play',
        '["54-segment prize wheel", "Random multiplier up to 500x on every spin", "Live host"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/megawheel',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Lightning Roulette',
        'Lightning Roulette is similar to standard roulette games with additional features including Lucky Numbers and Lucky Payouts.',
        'lightningroulette',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/lightning-roulette-thumbnail.png',
        'TRACKED GAME SHOWS',
        NULL,
        500.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Lucky Numbers with multipliers", "Lucky Payouts from 50x to 500x", "Straight up bet pays 30:1"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/lightningroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'XXXTreme Lightning Roulette',
        'XXXTreme Lightning Roulette is the extreme version of the original Lightning Roulette, with the potential to win up to 2,000x your bet.',
        'xxxtremelightningroulette',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/logo-xxxtreme-lightning-roulette.png',
        'TRACKED GAME SHOWS',
        NULL,
        2000.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Multipliers up to 2,000x", "Chain Lightning feature", "One to five lightning numbers per round"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/xxxtremelightningroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Red Door Roulette',
        'This new offering from Evolution Gaming brilliantly merges the award-winning Lightning Roulette with the suspense of Crazy Time''s Bonus game.',
        'reddoorroulette',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/cms-dev/red_door_roulette_logo_eng_2023_08_7800567d54_1_e3966a2f60.svg',
        'TRACKED GAME SHOWS',
        '97.30%',
        20.0,
        0.1,
        1000.0,
        'November 8th, 2023',
        'evolution',
        '["3-15 Bonus Numbers per round", "Crazy Time Bonus game", "Random multipliers up to 20x"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/reddoorroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Gold Vault Roulette',
        NULL,
        'goldvaultroulette',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/GoldVaultRoulette/gold-vault-roulette-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        NULL,
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/goldvaultroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Crazy Coin Flip',
        'Crazy Coin Flip is a RNG slot / Live Casino hybrid from Evolution, with two video slot rounds, and one live game show round with the popular coin flip made popular in Crazy Time.',
        'crazycoinflip',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,f_auto,q_auto,c_scale,h_373,w_457/Coin%20Flip%20Images/ccf-logo.png',
        'TRACKED GAME SHOWS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["RNG Slot qualifying round", "Live Coin Flip bonus round", "XXXTreme spin modes"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/crazycoinflip',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Immersive Roulette',
        'A unique high quality game with full HD view of the roulette wheel from multiple angles, as well as close-ups of the presenter.',
        'immersiveroulette',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/thumbnail-300x220-immersive-roulette.png',
        'TRACKED GAME SHOWS',
        '97.3%',
        NULL,
        0.1,
        1000.0,
        '2013',
        'evolution',
        '["Multi-camera visuals", "Slow motion replay feature", "200 frames per second HD video"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/immersiveroulette',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Lightning Baccarat',
        'Classic baccarat enhanced with high-payout RNG multipliers. In every round, 1 to 5 randomly generated Lightning Cards appear, adding multipliers from 2x to 8x.',
        'lightningbaccarat',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/thumbnail-300x220-lightning-baccarat.png',
        'TRACKED GAME SHOWS',
        '98.76% (Player)',
        512.0,
        1.0,
        5000.0,
        '2020',
        'evolution',
        '["Lightning Round with multipliers", "Multipliers up to 512x", "20% Lightning Fee"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/lightningbaccarat',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Cash or Crash Live',
        'The goal of the game is to climb a 20-step ladder-style paytable as high as you can, chasing a max win of up to 50,000 times your stake.',
        'cashorcrashlive',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/cash-or-crash-thumbnail.png',
        'TRACKED GAME SHOWS',
        '99.59%',
        50000.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["20-step paytable ladder", "Green, Red, and Gold ball mechanics", "Strategic choices: continue, take half, or take all"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/cashorcrashlive',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Fan Tan Live',
        'Fan Tan is an ancient Asian game where players predict the amount of remaining beads at the end of the game round after being sorted into groups of four.',
        'fantanlive',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/thumbnail-300x220-fan-tan.png',
        'LIVE STREAMS',
        '96.25% - 98.75%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Based on ancient Asian game", "Standard and Advanced betting modes", "Multiple bet types (Nim, Kwok, Ssh)"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/fantanlive',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'War Live',
        'Evolution War is a modern take on the classic Casino War card game. You and the dealer each receive a card, and the higher card wins.',
        'warlive',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/cms-prod/logoevo_war_77df58e424.png',
        'LIVE STREAMS',
        '96.27% - 96.56%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Simple ''higher card wins'' rule", "Go To War on a Tie", "Side bet on a Tie result"]',
        true,
        'https://api.casinoscores.com/svc-evolution-game-events/api/warlive',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Mega Ball',
        'Mega Ball by Evolution Gaming is a Live casino game show which features up to 2 Mega Ball bonus rounds, combining mechanics of lottery and bingo.',
        'megaball',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/mega-ball.png',
        'LIVE STREAMS',
        '95.50%',
        100.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Bingo/Lottery hybrid", "Mega Ball bonus round with 5x-100x multiplier", "Purchase up to 200 cards per round"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/megaball',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Free Bet Blackjack',
        'Based on popular land-based Blackjack, it includes the added attraction of selected free Double Down and Split Bets.',
        'freebetblackjack',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/thumbnail-300x220-free-bet-blackjack.png',
        'LIVE STREAMS',
        '98.45%',
        NULL,
        1.0,
        5000.0,
        NULL,
        'evolution',
        '["Free Double Down bets on 9, 10, 11", "Free Split bets on pairs (except 10s)", "Four optional side bets", "Unlimited seating"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/freebetblackjack',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Extra Chilli Epic Spins',
        'Evolution presents Extra Chilli Epic Spins, bringing the popular Megaways mechanic from Big Time Gaming to the live game show studio.',
        'extrachilliepicspins',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Extra%20Chilli%20Epic%20Spins/extra-chilli-epic-spins.png',
        'LIVE STREAMS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Megaways slot mechanic", "Piñata feature with multipliers or bonus triggers", "Gamble Wheels to win extra free spins"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/extrachilliepicspins',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Video Poker',
        'Evolution Video Poker Live brings the excitement of classic video poker with a twist of real-time live video gameplay.',
        'videopoker',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/video-poker/video_poker_logo-min.png',
        'LIVE STREAMS',
        '97% - 99%',
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Play up to 100 hands at once", "Multiple variations (Jacks or Better, Deuces Wild, etc.)", "First-Person mode available"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/videopoker',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Imperial Quest',
        'A reskin of Dream Catcher with an Eastern theme, this game delivers high production quality and thrilling gameplay with win multipliers and fun, professional hosts.',
        'imperialquest',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Imperial%20Quest/imperial-quest-thumbnail.png',
        'LIVE STREAMS',
        NULL,
        20000.0,
        0.1,
        1000.0,
        NULL,
        'evolution',
        '["Asian-themed money wheel", "2x and 7x win multiplier segments", "Potential combined multiplier up to 20,000x"]',
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/imperialquest',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Dead or Alive Saloon',
        NULL,
        'deadoralive',
        'https://res.cloudinary.com/dlkdffnou/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/Dead%20Or%20Alive%20-%20Salon/dead-or-alive-logo.png',
        'LIVE STREAMS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        NULL,
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/deadoralive',
        NOW(),
        NOW()
    ),
    (
        gen_random_uuid(),
        'Live Craps',
        NULL,
        'livecraps',
        'https://res.cloudinary.com/casinogrounds/image/upload/dpr_auto,w_auto,f_auto,q_auto,c_scale/CasinoScores/craps-live.png',
        'LIVE STREAMS',
        NULL,
        NULL,
        0.1,
        1000.0,
        NULL,
        'evolution',
        NULL,
        false,
        'https://api.casinoscores.com/svc-evolution-game-events/api/livecraps',
        NOW(),
        NOW()
    )
ON CONFLICT ("name") DO NOTHING;